version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080" 
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  
